spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/anonapp_db
    username: movage
    password: 1024
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: prod

  #logging:
  #  level:
  #    org.springframework.data.rest: debug

  #spring:
  #  data:
  #    rest:
  #      base-path: /api
