spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update



---

spring:
  profiles: prod

  #logging:
  #  level:
  #    org.springframework.data.rest: debug

  #spring:
  #  data:
  #    rest:
  #      base-path: /api
