spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update

  datasource:
    platform: DB
    url: jdbc:postgresql://CONNECT_URL
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver

---

spring:
  profiles: prod

  #logging:
  #  level:
  #    org.springframework.data.rest: debug

  #spring:
  #  data:
  #    rest:
  #      base-path: /api
